#:schema ./override-schema.json
# Course 21A special subjects (fall 2025)

['20.S900']
name = "The Bioeconomy and Society"
description = "Characterizes and examines the transformation of the production of fuels, foods, materials, and medicines through sustainable processes based on bacteria, fungi, algae, and plants, to inaugurate a biologically-based economy, or \"bioeconomy.\" Studies this developing bioeconomy and its antecedent political, technological, and cultural events, as well as its potential social impacts. Includes guest speakers from policy, industry, and academia. Discusses the scientific research which offers outside perspectives on opportunities and challenges that the bioeconomy presents. Students work in project-based teams throughout the term to analyze the historical and contemporary dimensions of one feature of the bioeconomy."
meets = "STS.059, 20.S948"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
inCharge = "R. Scheffler and M. Bathe"

['20.S948']
name = "The Bioeconomy and Society"
description = "Characterizes and examines the transformation of the production of fuels, foods, materials, and medicines through sustainable processes based on bacteria, fungi, algae, and plants, to inaugurate a biologically-based economy, or \"bioeconomy.\" Studies this developing bioeconomy and its antecedent political, technological, and cultural events, as well as its potential social impacts. Includes guest speakers from policy, industry, and academia. Discusses the scientific research which offers outside perspectives on opportunities and challenges that the bioeconomy presents. Students work in project-based teams throughout the term to analyze the historical and contemporary dimensions of one feature of the bioeconomy."
meets = "STS.059, 20.S900"
lectureUnits = 3
labUnits = 0
preparationUnits = 9
inCharge = "R. Scheffler and M. Bathe"
